# CircleCI configuration file
orbs:
  codecov: codecov/codecov@3.3.0
  slack:   circleci/slack@4.12.5
version: 2.1

executors:
  app-executor:
    docker:
      - image: cimg/node:18.17.1
      - image: 'cibuilds/base:latest'
    working_directory: ~/repo
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small
aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
     restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install

  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}


  - &zip-project
    run:
      name: Zip project
      command: |
          rm -rf node_modules
          zip Task.zip -r .
          echo "Zip successful"
  - &notify-on-fail

    slack/notify:
      event: fail
      channel: 'Task-app-build'   # name channel slack
      template: ''
      custom: |
        {
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "Job Failed. 🔴",
                "emoji": true
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Job*: ${CIRCLE_JOB}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Branch*:\n$CIRCLE_BRANCH"
                },
                {
                  "type": "mrkdwn",
                  "text": "*When*:\n$(date +'%m/%d/%Y %T')"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Build*:\n$CIRCLE_BUILD_NUM"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Author*:\n$CIRCLE_PROJECT_USERNAME"
                }
              ]
            },
            {
              "type": "actions",
              "elements": [
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "View Job"
                  },
                  "url": "${CIRCLE_BUILD_URL}"
                }
              ]
            }
          ]
        }

# haste este punto podemos tener active:
jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run linting
          command: npm run lint:check
      - *notify-on-fail

# formateo del codigo
  code-formatter-check:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run prettier check
          command: npm run prettier:check
      - *notify-on-fail


  notify-via-slack:
    executor: slack-executor
    steps:
      - run: echo "Slack notification"
      - slack/notify:
          event: 'always'
          channel: 'Task-app-build'
          template: ''
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ 👍 ✅ ${CIRCLE_BRANCH} branch backend deployment is complete. ✅ 👍 ✅",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*:\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n$CIRCLE_BUILD_NUM"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*:\n$CIRCLE_PROJECT_USERNAME"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }



workflows:
  build_and_deploy:
    jobs:
      - build
      - linting:
          requires:
            - build
          filters:
            branches:
               only:
                - develop
                - staging
                - main
      - code-formatter-check:
          requires:
            - linting
          filters:
            branches:
               only:
                - develop
                - staging
                - main
      - unit-test:
          requires:
            - code-formatter-check
          filters:
            branches:
               only:
                - develop
                - staging
                - main

      - notify-via-slack:
          requires:
            - unit-test
          filters:
            branches:
               only:
                - develop
                - staging
                - main
      - hold:
          type: approval
          requires:
            - notify-via-slack

      - Task-destroy:
          requires:
            - hold
          filters:
            branches:
              only:
                - develop
                - staging
                - main
